@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs



Class UniqueStudentList
Class Student
Class Address
Class Email
Class Name
Class Phone
Class Tag
Class NOK

Class UniqueClassList
Class TuitionClass
Class ClassName
Class ClassTiming
Class Rate
Class Location
Class StudentNameList

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueStudentList
UniqueStudentList --> "~* all" Student
Student *--> "1" Name
Student *--> "1" Phone
Student *--> "1" Email
Student *--> "1" Address
Student *--> "*" Tag
Student *--> "1" NOK

AddressBook *--> "1" UniqueClassList
UniqueClassList --> "~* all" TuitionClass
TuitionClass *--> "1" ClassName
TuitionClass *--> "1" ClassTiming
TuitionClass *--> "1" Rate
TuitionClass *--> "1" Location
TuitionClass *--> "1" StudentNameList


Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

ModelManager -->"~* filtered" Student
ModelManager -->"~* filtered" TuitionClass
@enduml
