@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyTimestable <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class Timestable
Class ReadOnlyTimestable
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Class UniqueStudentList
Class UniqueClassList

package TuitionClass <<Rectangle>> {
}
package Student <<Rectangle>> {
}



}



Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

Timestable .up.|> ReadOnlyTimestable

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyTimestable
ModelManager -left-> "1" Timestable
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

Timestable *--> "1" UniqueStudentList
UniqueStudentList --> "~* all" Student

Timestable *--> "1" UniqueClassList
UniqueClassList -right-> "~* all" TuitionClass

ModelManager -->"~* filtered" Student
ModelManager -->"~* filtered" TuitionClass
@enduml
