    @startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Interface CommandObserver <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
'Class StudentListPanel
'Class StudentCard
Class StatusBarFooter
Class CommandBox
Enum TabName <<Enumeration>>

package TimetableUi <<Rectangle>> {
}

package ClassesUi <<Rectangle>> {
}

package StudentsUi <<Rectangle>> {
}

}
package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .right.|> Ui
UiManager -down-> "1" MainWindow
MainWindow .right.|> CommandObserver
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow -down-> "0..1" HelpWindow

'MainWindow *-down-> "1" StudentListPanel
MainWindow *-down-> "1" TimetableUi
MainWindow *-down-> "1" ClassesUi
MainWindow *-down-> "1" StudentsUi
MainWindow *-down-> "1" StatusBarFooter

'StudentListPanel -down-> "*" StudentCard
MainWindow -down-|> UiPart
ResultDisplay --|> UiPart
CommandBox --|> UiPart
'StudentListPanel --|> UiPart
'StudentCard --|> UiPart
ClassesUi --|> UiPart
TimetableUi --|> UiPart
StudentsUi --|> UiPart
StatusBarFooter --|> UiPart
HelpWindow --|> UiPart

'StudentCard .right.> Model
UiManager -up-> Logic
MainWindow -up-> Logic

Logic ---down-> CommandObserver : < Observes
Logic .down.> TabName

TimetableUi .up.> Model
ClassesUi .up.> Model
StudentsUi .up.> Model

'StudentListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter

MainWindow -[hidden]-|> UiPart

MainWindow .right.> TabName
@enduml
